# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "thalassophobia:glow_fish",
    "aquatica:yeti_crab",
    "villagergolemhealer:villagergolemhealer",
    "thalassophobia:bathotrap_natural_spawn",
    "aquaculture:pink_salmon",
    "thalassophobia:riffhead",
    "irons_spellbooks:archevoker",
    "villagergolemhealer:minigolem",
    "irons_spellbooks:catacombs_zombie",
    "minecraft:horse",
    "enemyexpansion:meature",
    "aquaculture:muskellunge",
    "minecraft:llama",
    "lush_rush:learcher",
    "benssharks:land_shark",
    "benssharks:whale_shark",
    "biomeswevegone:man_o_war",
    "minecraft:tadpole",
    "luminous_nether:basalt_executioner",
    "lush_rush:mossy_raid_3",
    "luminous_beasts:rare_vile_gator",
    "lush_rush:mossy_raid_2",
    "lush_rush:mossy_raid_5",
    "lush_rush:mossy_raid_4",
    "thalassophobia:cookie_cutter_shark",
    "just_in_nether:bullkin_brute",
    "enemyexpansion:trollenraged",
    "thalassophobia:maka_maka_natural_spawn",
    "undead_revamp2:invisiimmortal",
    "benssharks:greater_axodile",
    "enemyexpansion:troll",
    "minecraft:mooshroom",
    "minecraft:axolotl",
    "luminous_beasts:rare_stalker",
    "irons_spellbooks:summoned_vex",
    "lush_rush:goblin_farmer",
    "enemyexpansion:vampire",
    "thalassophobia:megalodon",
    "luminous_beasts:rare_hermit_king",
    "aquaculture:pacific_halibut",
    "creeperoverhaul:spruce_creeper",
    "iceandfire:siren",
    "thalassophobia:yeti_crab",
    "land_of_goblins:wither_fungus",
    "thalassophobia:reaverfish",
    "luminous_nether:soul_furnace",
    "thalassophobia:hesperornis",
    "thalassophobia:megastar",
    "thalassophobia:sunfish",
    "undead_revamp2:theordure",
    "undead_revamp2:theheavy",
    "thalassophobia:crab_spawn",
    "luminous_nether:poltergeist",
    "luminous_nether:the_furnace_2",
    "luminous_nether:the_furnace_3",
    "luminous_nether:piglin_ghost",
    "enemyexpansion:vampflyer",
    "irons_spellbooks:magehunter_vindicator",
    "undead_revamp2:clogger",
    "thalassophobia:dead_archelon",
    "minecraft:chicken",
    "minecraft:zombie",
    "iceandfire:dread_knight",
    "undead_revamp2:coppertar",
    "aquaculture:tambaqui",
    "thalassophobia:bathotrap_spawn",
    "minecraft:hoglin",
    "thalassophobia:baby_colossoteus",
    "land_of_goblins:desert_goblin",
    "aquaculture:brown_shrooma",
    "iceandfire:myrmex_swarmer",
    "lush_rush:lush_golem",
    "minecraft:zombified_piglin",
    "aquatica:dragonfish",
    "minecraft:sheep",
    "thalassophobia:maka_maka_in_ground",
    "benssharks:axodile",
    "land_of_goblins:beach_goblin",
    "thalassophobia:sea_phantom",
    "thalassophobia:colossoteus_sonar_attack",
    "spawn:octopus",
    "minecraft:ravager",
    "iceandfire:myrmex_soldier",
    "enemyexpansion:flutterfly",
    "iceandfire:pixie",
    "realmrpg_demons:demon",
    "land_of_goblins:thyster",
    "crittersandcompanions:dragonfly",
    "spawn:hamster",
    "iceandfire:myrmex_sentinel",
    "luminous_nether:soul_ember",
    "undead_revamp2:therabidus",
    "undead_revamp2:theposessive",
    "benssharks:leopard_shark",
    "realmrpg_demons:demon_minion",
    "creeperoverhaul:beach_creeper",
    "undead_revamp2:thebidy",
    "lush_rush:adventurer_goblin",
    "chest_with_legs:ro_bin",
    "luminous_beasts:the_furnace",
    "undead_revamp2:the_moonflower",
    "thalassophobia:maka_maka",
    "land_of_goblins:goblig",
    "thalassophobia:ichthyosaurus_tamed",
    "creeperoverhaul:hills_creeper",
    "luminous_beasts:rare_phoenix_bird",
    "crittersandcompanions:otter",
    "just_in_nether:dullkin",
    "thalassophobia:bathotrap",
    "benssharks:megalodon",
    "creeperoverhaul:bamboo_creeper",
    "land_of_goblins:shiny_undead",
    "benssharks:basking_shark",
    "luminous_beasts:sea_viper",
    "thalassophobia:hesperornis_spawn",
    "undead_revamp2:thehorrors",
    "luminous_beasts:vile_gator",
    "inka:viraicocha_magic_square",
    "aquatica:gulper_eel",
    "undead_revamp2:bigsucker",
    "iceandfire:myrmex_worker",
    "minecraft:cat",
    "luminous_beasts:tree_ent",
    "minecraft:tropical_fish",
    "spawn:tuna",
    "realmrpg_demons:imp_guard",
    "thalassophobia:megastar_spawn",
    "realmrpg_demons:ancient_demon_lord",
    "minecraft:zombie_villager",
    "luminous_nether:piglin_executioner_2",
    "luminous_nether:piglin_executioner_3",
    "minecraft:giant",
    "enemyexpansion:botfly",
    "chococraft:chocobo",
    "mowziesmobs:lantern",
    "aquaculture:atlantic_herring",
    "luminous_beasts:stalker",
    "chest_with_legs:stone_egg_e",
    "spawn:seahorse",
    "creeperoverhaul:cave_creeper",
    "luminous_beasts:witch_doctor",
    "benssharks:lemon_shark",
    "aquaculture:bluegill",
    "minecraft:husk",
    "thalassophobia:bull_shark",
    "undead_revamp2:axestrom",
    "inka:viraicocha_sun",
    "lush_rush:lush_spike",
    "lush_rush:elite_learauder",
    "mowziesmobs:umvuthana",
    "call_of_yucutan:golden_guard",
    "luminous_nether:ember",
    "luminous_nether:piglin_executioner",
    "minecraft:donkey",
    "mowziesmobs:umvuthana_crane_player",
    "minecraft:piglin_brute",
    "thalassophobia:maka_maka_swim",
    "aquaculture:jellyfish",
    "luminous_nether:glider",
    "iceandfire:ice_dragon",
    "enemyexpansion:tarantula",
    "thalassophobia:anomalocaris",
    "benssharks:whitetip_shark",
    "luminous_nether:guzzleghast",
    "aquaculture:blackfish",
    "thalassophobia:plesiosaur",
    "minecraft:parrot",
    "irons_spellbooks:apothecarist",
    "call_of_yucutan:kukulkan",
    "aquaculture:carp",
    "call_of_yucutan:undead_warrior",
    "enemyexpansion:wasp",
    "enemyexpansion:intruder",
    "creeperoverhaul:desert_creeper",
    "iceandfire:sea_serpent",
    "lush_rush:mosswarder",
    "spawn:sunfish",
    "aquaculture:boulti",
    "luminous_nether:the_furnace",
    "inka:vibration_entity",
    "minecraft:mule",
    "benssharks:blacktip_reef_shark",
    "minecraft:vindicator",
    "call_of_yucutan:chaac",
    "luminous_beasts:tamed_stalker",
    "crittersandcompanions:leaf_insect",
    "thalassophobia:leedsichthys",
    "creeperoverhaul:mushroom_creeper",
    "aquaculture:synodontis",
    "undead_revamp2:thelurker",
    "luminous_nether:piglin_cultist_leader",
    "irons_spellbooks:debug_wizard",
    "thalassophobia:manta",
    "lush_rush:goblin_mage",
    "irons_spellbooks:spectral_steed",
    "inka:viraicocha_solar_beam",
    "luminous_beasts:crimson_spitter",
    "undead_revamp2:thespitter",
    "variantsandventures:murk",
    "creeperoverhaul:badlands_creeper",
    "creeperoverhaul:snowy_creeper",
    "aquaculture:catfish",
    "benssharks:blue_shark",
    "luminous_beasts:ember",
    "thalassophobia:octus",
    "mowziesmobs:bluff",
    "iceandfire:lightning_dragon",
    "realmrpg_demons:imp",
    "minecraft:pig",
    "aquaculture:atlantic_halibut",
    "creeperoverhaul:swamp_creeper",
    "iceandfire:fire_dragon",
    "minecraft:cod",
    "undead_revamp2:theswarmer",
    "aquaculture:red_grouper",
    "undead_revamp2:theimmortal",
    "luminous_beasts:soul_furnace",
    "minecraft:cow",
    "aquaculture:rainbow_trout",
    "benssharks:tiger_shark",
    "lush_rush:goblin_miner",
    "benssharks:thalassoger",
    "benssharks:pilot_fish",
    "luminous_nether:revenant_skeleton",
    "iceandfire:dread_scuttler",
    "minecraft:salmon",
    "crittersandcompanions:dumbo_octopus",
    "enemyexpansion:scorpion",
    "mowziesmobs:naga",
    "undead_revamp2:bomber",
    "thalassophobia:anglerfish",
    "thalassophobia:megapiranha",
    "spawn:angler_fish",
    "mowziesmobs:ferrous_wroughtnaut",
    "minecraft:rabbit",
    "minecraft:pillager",
    "minecraft:zoglin",
    "aquaculture:piranha",
    "netherexp:ecto_slab",
    "undead_revamp2:thehorrorsdecoys",
    "variantsandventures:verdant",
    "enemyexpansion:starved",
    "creeperoverhaul:jungle_creeper",
    "chest_with_legs:shadow_chester",
    "spawn:clam",
    "irons_spellbooks:cryomancer",
    "enemyexpansion:invisicreeper",
    "lush_rush:lush_mage",
    "thalassophobia:crab_natural_spawn",
    "iceandfire:gorgon",
    "undead_revamp2:thesmoker",
    "aquaculture:arrau_turtle",
    "inka:viraicocha_solar_shot",
    "luminous_nether:warped_king",
    "minecraft:sniffer",
    "thalassophobia:sea_bird_spawn",
    "thalassophobia:gulper_eel",
    "iceandfire:cockatrice",
    "lush_rush:amethyst_spike",
    "benssharks:goblin_shark",
    "thalassophobia:colossoteus",
    "benssharks:krill",
    "realmrpg_demons:chort",
    "mowziesmobs:umvuthana_follower_player",
    "iceandfire:deathworm",
    "undead_revamp2:crackleball",
    "undead_revamp2:thehunter",
    "thalassophobia:tusoteuthis",
    "luminous_nether:spirit",
    "inka:viraicocha_sun_projectile",
    "enemyexpansion:goblin",
    "minecraft:trader_llama",
    "lush_rush:lush_goblin",
    "irons_spellbooks:necromancer",
    "undead_revamp2:thepregnant",
    "iceandfire:dread_lich",
    "undead_revamp2:weakspot",
    "aquaculture:bayad",
    "lush_rush:bloom",
    "thalassophobia:liopleurodon",
    "aquatica:anglerfish",
    "minecraft:dolphin",
    "luminous_beasts:pumpkin_minion",
    "thalassophobia:sea_sludge_spawn",
    "crittersandcompanions:jumping_spider",
    "undead_revamp2:slaveman",
    "undead_revamp2:invisiclogger",
    "enemyexpansion:crawler",
    "minecraft:bee",
    "aquaculture:perch",
    "minecraft:illusioner",
    "thalassophobia:crab",
    "luminous_nether:crimson_walker",
    "undead_revamp2:thebeartamer",
    "thalassophobia:sea_sludge_natural_spawn",
    "thalassophobia:sea_sludge",
    "thalassophobia:yeti_crab_natural_spawn",
    "aquatica:scaly_foot_gastropod",
    "mowziesmobs:foliaath",
    "luminous_beasts:yeti",
    "mowziesmobs:frostmaw",
    "minecraft:drowned",
    "luminous_nether:mushlin_king_3",
    "luminous_nether:mushlin_king_2",
    "aquaculture:arapaima",
    "undead_revamp2:thedungeon",
    "lush_rush:goblin_king",
    "benssharks:bonnethead_shark",
    "undead_revamp2:thespectre",
    "netherexp:apparition",
    "minecraft:wandering_trader",
    "luminous_nether:zombie_piglin_cultist",
    "benssharks:mako_shark",
    "biomeswevegone:oddion",
    "luminous_nether:zombie_piglin_cultist_leader",
    "aquatica:telescope_leviathan",
    "undead_revamp2:propball_1",
    "benssharks:greatwhiteshark",
    "iceandfire:stone_statue",
    "thalassophobia:basking_shark",
    "crittersandcompanions:sea_bunny",
    "undead_revamp2:therod",
    "luminous_beasts:piglin_executioner",
    "spawn:ant",
    "mowziesmobs:umvuthana_raptor",
    "thalassophobia:sonar_boom",
    "crittersandcompanions:red_panda",
    "aquatica:horse_cucumber",
    "aquaculture:atlantic_cod",
    "thalassophobia:eurypterid",
    "benssharks:nurse_shark",
    "minecraft:pufferfish",
    "aquaculture:starshell_turtle",
    "minecraft:fox",
    "enemyexpansion:ladybug",
    "mowziesmobs:umvuthana_crane",
    "simplyswords:simplybeeentity",
    "luminous_beasts:rare_crimson_spitter",
    "call_of_yucutan:ahaw",
    "thalassophobia:sea_bird",
    "enemyexpansion:silverqueenbodiless",
    "land_of_goblins:cave_goblin",
    "benssharks:barracuda",
    "creeperoverhaul:savannah_creeper",
    "luminous_nether:mushlin_king",
    "inka:particlesviraicocha",
    "minecraft:polar_bear",
    "inka:incawarrior_2",
    "inka:incawarrior_1",
    "inka:incawarrior_3",
    "aquaculture:brown_trout",
    "minecraft:turtle",
    "aquatica:manglerfish",
    "variantsandventures:gelid",
    "enemyexpansion:direwolf",
    "luminous_beasts:horseless_headsman",
    "irons_spellbooks:dead_king",
    "thalassophobia:orthoceras",
    "call_of_yucutan:updater",
    "undead_revamp2:thewolf",
    "mowziesmobs:umvuthana_follower_raptor",
    "undead_revamp2:thebidyupside",
    "thalassophobia:ammonita",
    "luminous_beasts:baby_phoenix",
    "irons_spellbooks:priest",
    "iceandfire:troll",
    "luminous_beasts:rare_tree_ent",
    "benssharks:remora",
    "inka:headclava",
    "luminous_beasts:bone_stalker",
    "chest_with_legs:chester",
    "minecraft:bat",
    "iceandfire:amphithere",
    "luminous_beasts:phoenixbird",
    "thalassophobia:archelon",
    "thalassophobia:dunkleosteus",
    "thalassophobia:megastar_natural_spawn",
    "inka:cuy",
    "iceandfire:stymphalian_bird",
    "benssharks:sawshark",
    "netherexp:banshee",
    "iceandfire:hippogryph",
    "lush_rush:mossy_raid",
    "luminous_beasts:the_scarecrow",
    "minecraft:panda",
    "luminous_beasts:soul_ember",
    "aquatica:barreleye",
    "just_in_nether:bullkindar",
    "thalassophobia:helicoprion",
    "luminous_beasts:rare_mummy",
    "undead_revamp2:theskeeper",
    "thalassophobia:yeti_crab_spawn",
    "inka:capac",
    "luminous_beasts:mummy",
    "undead_revamp2:lechery",
    "luminous_nether:mushlin_bumper",
    "inka:quake_entity",
    "luminous_beasts:rare_executioner",
    "iceandfire:cyclops",
    "lush_rush:learauder",
    "realmrpg_demons:demon_lord",
    "land_of_goblins:crabtilus",
    "lush_rush:golbin_guard",
    "thalassophobia:dead_archelon_spawn",
    "thalassophobia:maka_maka_spawn",
    "luminous_beasts:scarecrow_minion",
    "irons_spellbooks:summoned_polar_bear",
    "just_in_nether:bullkin",
    "irons_spellbooks:cultist",
    "netherexp:wisp",
    "aquaculture:tuna",
    "undead_revamp2:neocrorines",
    "inka:apuinti",
    "enemyexpansion:vampbiter",
    "aquatica:isopod",
    "undead_revamp2:sucker",
    "thalassophobia:panderodus",
    "call_of_yucutan:mitnal_monkey",
    "enemyexpansion:goblin_fear",
    "thalassophobia:alpha_reaverfish",
    "minecraft:frog",
    "crittersandcompanions:shima_enaga",
    "spawn:snail",
    "enemyexpansion:drone",
    "enemyexpansion:huntsman",
    "thalassophobia:electrophorus",
    "iceandfire:hydra",
    "luminous_nether:gilded_cultist",
    "minecraft:evoker",
    "iceandfire:dread_ghoul",
    "crittersandcompanions:ferret",
    "luminous_beasts:gilded_ent",
    "aquaculture:smallmouth_bass",
    "variantsandventures:thicket",
    "thalassophobia:cnidaria",
    "creeperoverhaul:ocean_creeper",
    "luminous_beasts:rare_yeti",
    "creeperoverhaul:dark_oak_creeper",
    "aquaculture:minnow",
    "just_in_nether:pigmar",
    "luminous_beasts:rare_baby_phoenix",
    "luminous_beasts:woodland_witch_doctor",
    "benssharks:bull_shark",
    "luminous_beasts:rare_bone_stalker",
    "iceandfire:dread_horse",
    "undead_revamp2:invisilehcery",
    "thalassophobia:basilosaurus",
    "undead_revamp2:thesomnolence",
    "irons_spellbooks:summoned_zombie",
    "mowziesmobs:grottol",
    "aquaculture:red_shrooma",
    "mowziesmobs:baby_foliaath",
    "minecraft:goat",
    "enemyexpansion:slugger",
    "aquaculture:gar",
    "iceandfire:dread_beast",
    "netherexp:vessel",
    "luminous_nether:piglin_cultist",
    "thalassophobia:vertebrat",
    "mowziesmobs:umvuthi",
    "thalassophobia:ichthyosaurus",
    "just_in_nether:zombiefied_bullkin",
    "inka:viraicocha",
    "iceandfire:hippocampus",
    "thalassophobia:xiphactinus",
    "iceandfire:myrmex_queen",
    "aquatica:bonefish",
    "luminous_nether:cultist_archer",
    "undead_revamp2:smokesmitter",
    "iceandfire:ghost",
    "luminous_nether:cultist_rider",
    "luminous_beasts:hermit_king",
    "enemyexpansion:silverqueen",
    "iceandfire:myrmex_royal",
    "irons_spellbooks:pyromancer",
    "spawn:sea_cow",
    "aquaculture:box_turtle",
    "undead_revamp2:invisiblebidy",
    "benssharks:greenland_shark",
    "call_of_yucutan:blowgun_huracan",
    "creeperoverhaul:dripstone_creeper",
    "irons_spellbooks:summoned_skeleton",
    "luminous_beasts:sand_crab",
    "iceandfire:dread_thrall",
    "crittersandcompanions:koi_fish",
    "aquatica:giant_dragonfish",
    "irons_spellbooks:citadel_keeper",
    "aquatica:gomblore",
    "aquaculture:pollock",
    "benssharks:cookiecutter_shark",
    "thalassophobia:mosasaur",
    "minecraft:piglin",
    "thalassophobia:hammerhead_shark",
    "thalassophobia:zapfin",
    "enemyexpansion:equestrian",
    "enemyexpansion:sprinter",
    "undead_revamp2:flame",
    "undead_revamp2:thegliter",
    "aquaculture:capitaine",
    "call_of_yucutan:ah_puch",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "luminous_beasts:rare_sea_viper",
    "land_of_goblins:creeptus",
    "spawn:herring",
    "netherexp:stampede",
    "minecraft:ocelot",
    "lush_rush:elite_learcher",
    "chest_with_legs:hutch",
    "minecraft:wolf",
    "enemyexpansion:faller",
    "thalassophobia:shark",
    "undead_revamp2:deadclogger"
]
